config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'genres/index'
  devise_for :admins
  # SNS_login_or_signup_routing
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  def devise_scope(scope)
    constraint = lambda do |request|
      request.env['devise.mapping'] = Devise.mappings[scope]
      true
    end

    constraints(constraint) do
      yield
    end
  end

  # homes_routing
  root 'homes#top'
  get 'homes/about' => 'about'
  get 'welcome' => 'homes#welcome', as: 'welcoming'
  get 'redirect' => 'homes#redirect'

  # Users_routing
  resources :users do
    resource :relationship, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resources :contacts, only: [:new, :index, :show, :create]
    resources :messages, only: :create
    resources :rooms, only: [:create, :show, :index]
  end
  get 'withdrawal' => 'users#withdrawal'

  # User_favorite_routing
  get '/users/:id/favorites' => 'favorites#index', as: 'user_favorites'
  get '/users/:id/favorite_comments' => 'comment_favorites#index', as: 'user_favorite_comments'

  # Genre_routing
  get '/genres' => 'genres#index'
  get '/genres/:genre_id/posts' => 'posts#category', as: 'category_posts'

  # Posts_routing
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end


  # Admin_routing
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show, :update]
    resources :genres, except: [:new]
  end

  get 'search' => 'search#search'

  # Comment_favortite_routing
  resources :comments do
    resource :comment_favorites, only: [:create, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :genre
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :comment_favorites, dependent: :destroy

  attachment :image

  
  # バリデーション
  validates :body, presence: true, length:{maximum: 140}
  
  # ユーザーがそのコメントをお気に入りしているか判断する
  def comment_favorited_by?(user)
    comment_favorites.where(user_id: user.id).exists?
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  attachment :image

  enum is_support_status: [:"対応待ち", :"対応中", :"対応済み"]

  # :バリデーション
  validates :title, presence: true
  validates :body, presence: true

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  # カテゴリーを通してポストを取得、上下させない
  has_many :categories, dependent: :destroy
  has_many :posts, through: :categories, dependent: :destroy

  # バリデーション
  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  # カテゴリーを通してジャンルを取得するので、上下させない
  has_many :categories, dependent: :destroy
  has_many :genres, through: :categories

  attachment :image

  # バリデーション
  validates :title, presence: true
  validates :image, presence: true
  validates :body, presence: true
  validates :genres, presence: true
  validates :closed_on, presence: true

  # ユーザーがその投稿をお気に入りしているか判断する
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 投稿一覧のソート定義
  def self.sort(selection)
    case selection
    when "new"
      return all.order(created_at: :DESC)
    when "old"
      return all.order(created_at: :ASC)
    when "commentable"
      return all.order(closed_on: :DESC)
    when "many_comment"
      return joins(:comments).group(:post_id).order('count(post_id) desc')
    when "many_favorite"
      return joins(:favorites).group(:post_id).order('count(post_id) desc')
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
        #  , omniauth_providers: [:google, :twitter]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_posts, through: :favorites, source: :post
  has_many :comment_favorites, dependent: :destroy
  has_many :favorited_comments, through: :comment_favorites, source: :comment
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :image

  # バリデーション
  validates :name, presence: true, length: {maximum: 20}
  validates :introduction, length: {maximum: 200}


  # 自分がフォローしているユーザーとの関連
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  # 自分がフォローされているユーザーとの関連
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    # 今自分（引数のuser)がフォローしようとしているユーザー（レシーバー）がフォローされているユーザーの中から自分がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  protected

  def self.find_for(auth)
    # userが登録されているか確認
    user = User.find_by(email: auth.info.email)
    # なければ作るように処理
    unless user
      user = User.create(email: auth.info.email,
                         name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20],
                         meta:     auth.to_yaml
                        )
    end
    # 作ったユーザーを返してログイン
    return user
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @method = params["search"]["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == "user"
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'forward'
        User.where('name LIKE ?', content+'%')
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content)
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == "post"
      if method == 'perfect'
        Post.where(body: content)
      elsif method == 'forward'
        Post.where('body LIKE ?', content+'%')
      elsif method == 'backward'
        Post.where('body LIKE ?', '%'+content)
      else
        Post.where('body LIKE ?', '%'+content+'%')
      end
    else
      if method == 'perfect'
        Comment.where(body: content)
      elsif method == 'forward'
        Comment.where('body LIKE ?', content+'%')
      elsif method == 'backward'
        Comment.where('body LIKE ?', '%'+content)
      else
        Comment.where('body LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/search/search.html.erb
<%# 検索ページ %>
<h2>
  "<%= @content %>"の検索結果
</h2>
<% if user_signed_in? %>
  <% if @model == 'user' %>
    <% @records.each do |user| %>
      <div class="users-index">
        <%= link_to user_path(user.id) do %>
          <%= render "users/info" , user: user %>
        <% end %>
      </div>
    <% end %>
    <% else %>
      <% @records.each do |post| %>
        <%= render 'posts/list', post: post %>
      <% end %>
  <% end %>

<% elsif admin_signed_in? %>

    <% if @model == 'user' %>
      <% @records.each do |user| %>
        <div class="users-index">
          <%= link_to admin_user_path(user.id) do %>
            <%= render 'admin/users/admin_user_info', user: user %>
          <% end %>
        </div>
      <% end %>
    <% elsif @model == 'post' %>
      <% @records.each do |post| %>
        <%= render 'admin/posts/list', post: post %>
      <% end %>
    <% else %>
      <% @records.each do |comment| %>
        <div class="comment-favorites-wrapper">
          <table>
            <tr class="comment-area">
              <td>
                <%= link_to user_path(comment.user.id) do %>
                  <%= attachment_image_tag comment.user, :image, :fill, 50, 50, fallback: "no_image.jpg" , size:'50x50' ,class: "user-icon"%>
                <% end %>
              </td>
              <td>
                <%= link_to user_path(comment.user.id) do %>
                投稿者  :  <%= comment.user.name %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td class="comment-image">
                <%= attachment_image_tag comment, :image,  fallback: "no_image.jpg" , size:'100%, 100%', class: "comment-image" %>
              </td>
            </tr>
            <tr>
              <td>コメント</td>
              <td class="comment-body-area">
                <%= safe_join(comment.body.split("\n"), tag(:br)) %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td class="comment-favorites-link">
                <%= link_to admin_post_path(comment.post) do %>
                  この投稿ページへ行く
                <% end %>
              </td>
            </tr>
          </table>
        </div>
    <% end %>
  <% end %>
<% end %>