config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'genres/index'
  devise_for :admins
  # SNS_login_or_signup_routing
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  def devise_scope(scope)
    constraint = lambda do |request|
      request.env['devise.mapping'] = Devise.mappings[scope]
      true
    end

    constraints(constraint) do
      yield
    end
  end

  # homes_routing
  root 'homes#top'
  get 'homes/about' => 'about'
  get 'welcome' => 'homes#welcome', as: 'welcoming'
  get 'redirect' => 'homes#redirect'

  # Users_routing
  resources :users do
    resource :relationship, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resources :contacts, only: [:new, :index, :show, :create]
    resources :messages, only: :create
    resources :rooms, only: [:create, :show, :index]
  end
  get 'withdrawal' => 'users#withdrawal'

  # User_favorite_routing
  get '/users/:id/favorites' => 'favorites#index', as: 'user_favorites'
  get '/users/:id/favorite_comments' => 'comment_favorites#index', as: 'user_favorite_comments'

  # Genre_routing
  get '/genres' => 'genres#index'
  get '/genres/:genre_id/posts' => 'posts#category', as: 'category_posts'

  # Posts_routing
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end


  # Admin_routing
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show, :update]
    resources :genres, except: [:new]
  end

  get 'search' => 'search#search'

  # Comment_favortite_routing
  resources :comments do
    resource :comment_favorites, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
        #  , omniauth_providers: [:google, :twitter]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_posts, through: :favorites, source: :post
  has_many :comment_favorites, dependent: :destroy
  has_many :favorited_comments, through: :comment_favorites, source: :comment
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :image

  # バリデーション
  validates :name, presence: true, length: {maximum: 20}
  validates :introduction, length: {maximum: 200}


  # 自分がフォローしているユーザーとの関連
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  # 自分がフォローされているユーザーとの関連
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    # 今自分（引数のuser)がフォローしようとしているユーザー（レシーバー）がフォローされているユーザーの中から自分がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  protected

  def self.find_for(auth)
    # userが登録されているか確認
    user = User.find_by(email: auth.info.email)
    # なければ作るように処理
    unless user
      user = User.create(email: auth.info.email,
                         name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20],
                         meta:     auth.to_yaml
                        )
    end
    # 作ったユーザーを返してログイン
    return user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
      @user = User.find(params[:id])
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(
      :name, 
      :introduction, 
      :image, 
      :is_sex_flag, 
      :is_withdrawal_flag
    )
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  def google
    @user = User.find_for(request.env['omniauth.auth'])
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
    else
      if (data = request.env['omniauth.auth'])
        session['devise.omniauth_data'] = {
            email: data['info']['email'],
            provider: data['provider'],
            uid: data['uid']
        }
      end
      redirect_to new_user_registration_url
    end
  end


  # protected


  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    welcoming_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :current_user?, only: [:edit, :update]

  def index
    @users = User.all.order(created_at: "DESC").page(params[:page]).per(1)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: "DESC").page(params[:page]).per(1)
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :introduction,
      :image,
      :is_sex_flag,
      :is_withdrawal_flag
    )
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_favorites_list.html.erb
<table>
  <thead>
    <tr>
      <td>投稿者名</td>
      <td>投稿タイトル</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= post.user.name %></td>
      <td>
        <%= link_to post_path(post.id) do %>
          <%= attachment_image_tag post, :image, :fill, 50, 50, fallback: "no_image.jpg" , size:'50x50' %>
          <%= post.title %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/users/_info.html.erb
<div class="user-info-wrapper">
  <div>
    <div class="user-info-container">
        <%= attachment_image_tag user, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100', class: "user-icon" %>
      <div class="user-info-button">
        <% if user.id == current_user.id %>
            <% if check_page('users', 'show') %>
              <div class="user-info-edit-link">
                <%= link_to 'プロフィール編集する', edit_user_path(current_user) %>
              </div>
              <div class="user-info-follow-count">
                <%= link_to follows_user_path(user.id) do %>
                  フォロー数 :
                  <%= user.followings.count %>
                <% end %>
              </div>
              <div class="user-info-follow-count">
                <%= link_to followers_user_path(user.id) do %>
                  フォロワー数 :
                  <%= user.followers.count %>
                <% end %>
              </div>
            <% end %>
          <% else %>
        <table id="follow_button_<%= user.id %>">
          </tr>
            <%= render 'relationships/follow', user: user %>
          <tr>
        </table>
        <%# DMルームへのリンク %>
          <% if check_page('users', 'show') %>
            <% if (current_user.followed_by? user) && (user.followed_by? current_user) %>
              <div>
                <% if isRoom == true %>
                  <%= link_to user_room_path(user, roomId) do %>
                  <div class="dm-link">
                    <i class="far fa-envelope"></i>
                  </div>
                  <% end %>
                <% else %>
                  <%= form_for(room, url: user_rooms_path(user, roomId)) do |f| %>
                    <%= fields_for entry do |e| %>
                      <%= e.hidden_field :user_id, value: user.id %>
                    <% end %>
                    <div class="dm-link">
                      <%= button_tag sanitize('<i class="far fa-envelope"></i>', :type => "submit") %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <%# DMルームへのリンク %>
        <% end %>
    </div>
    </div>
  </div>
  <div class="user-info-name">
    <p>
      <%= user.name %><br>
    </p>
  </div>
  <% if check_page('users', 'index') %>
    <% if user.introduction.present? %>
      <div class="user-info-introduction">
        <p>
          <% if user.introduction.length > 10 %>
            <%= user.introduction.truncate(30) %>
          <% else %>
            <%= safe_join(user.introduction.split("\n"), tag(:br)) %>
          <% end %>
        </p>
      </div>
    <% else %>
      <div class="user-info-introduction"></div>
    <% end %>
  <% end %>
  <% if check_page('users', 'show') %>
    <% if user.introduction.present? %>
      <div class="user-info-introduction">
        <p>
          <%= safe_join(user.introduction.split("\n"), tag(:br)) %>
        </p>
      </div>
      <% else %>
        <% if user == current_user %>
          <div class="user-info-introduction">
            <%= link_to '自己紹介を追加する', edit_user_path(current_user) %>
          </div>
        <% else %>
          <div class="user-info-introduction"></div>
        <% end %>
    <% end %>
  <% end %>
  <div class="user-info-name-small">
    <%= link_to user_favorites_path(user.id) do %>
      お気に入りした投稿
      ”<%= user.favorites.count %>”  件
    <% end %>
  </div>
  <div class="user-info-name-small">
    <%= link_to user_favorite_comments_path(user.id) do %>
      お気に入りしたコメント
      ”<%= user.favorited_comments.count %>”  件
    <% end %>
  </div>
  <div class="user-info-name-small">
    投稿件数
    ”<%= user.posts.count %>”  件
  </div>
  <div class="user-info-name-small">
    コメント回数
    ”<%= user.comments.count %>”  件
  </div>

</div>

app/views/users/edit.html.erb
<%# ユーザー情報編集画面 %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2 style="color: red;"><%= @user.errors.count %> 件のエラーが発生しました。</h2>
    <ul style="color: red;">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<div class="users-edit-wrapper">
  <h2>ユーザー情報編集</h2>
  <%= form_for @user do |f| %>
    <div class="users-edit-name">
      <p>ユーザー名</p>
      <%= f.text_field :name, size: "40x10" %>
    </div>
    <div class="users-edit-image">
      <p>ユーザーアイコン</p>
      <%= f.file_field :image, id: "file", accept: 'image/jpg,image/jpeg,image/png' %>
    </div>
    <div>
    <div id="result" class="users-edit-prev">
      イメージプレビュー
    </div>
    </div>
    <div class="users-edit-introduction">
      <p>プロフィール</p>
      <%= f.text_area :introduction, size: "40x10" %>
    </div>
    <div class="users-edit-sex">
      <p>性別</p>
          <%= f.radio_button :is_sex_flag, :true, checked: true %>
          <%= f.label :is_sex_flag, "男性", {value: :true} %>
          <%= f.radio_button :is_sex_flag, :false %>
          <%= f.label :is_sex_flag, "女性", {value: :false} %>
    </div>
    <div class="user-edit-submit-button">
      <%= f.submit "ユーザー情報を更新する" %>
    </div>
  <% end %>
  <div>
    <%= link_to 'アカウントを削除', withdrawal_path(@user.id) %>
  </div>
</div>

app/views/users/followers.html.erb
<%# ユーザーのフォロワー一覧画面 %>
<h2>
  "<%= @user.name %>" さんのフォロワー一覧
  全<%= @users.count %> 件
</h2>
<% @users.each do |user| %>
  <%= link_to user_path(user.id) do %>
    <div class="follow-user-wrapper">
      <%= render "users/info" , user: user %>
    </div>
  <% end %>
<% end %>

app/views/users/follows.html.erb
<%# ユーザーのフォロー一覧画面 %>
<h2>
  "<%= @user.name %>" さんのフォロー一覧
  全<%= @users.count %> 件
</h2>
<% @users.each do |user| %>
  <%= link_to user_path(user.id) do %>
    <div class="follow-user-wrapper">
      <%= render "users/info" , user: user %>
    </div>
  <% end %>
<% end %>

app/views/users/index.html.erb
<%# ユーザー一覧（ユーザー目線） %>
<div class="users-index-wrapper">
  <h2>
    ユーザー一覧
    <i class="fas fa-users"></i>
  </h2>
  <div class="jscroll post-list">
    <% @users.each do |user| %>
      <div class="hidden">
        <%= paginate @users, class: "paginate" %>
      </div>
      <div class="users-index">
        <%= link_to user_path(user.id) do %>
          <%= render "users/info" , user: user %>
        <% end %>
      </div>
      <% end %>
      <div class="page-load-status">
         <p class="infinite-scroll-request"></p>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<%# マイページ %>
<h2 class="users-show-title">
  <%= @user.name %>'s Page
  <i class="fas fa-user"></i>
</h2>
<div class="users-show-wrapper">
  <%= render "users/info", user: @user, room: @room, isRoom: @isRoom, roomId: @roomId, entry: @entry %>
</div>

<div class="users-show-posts">
  <h2>
    <%= @user.name %>さんの投稿一覧
  </h2>
</div>

<div class="jscroll post-list">
  <% @posts.each do |post| %>
    <%= render 'posts/list', post: post %>
  <% end %>
  <div class="hidden">
    <%= paginate @posts, class: "paginate" %>
  </div>
  <div class="page-load-status">
    <p class="infinite-scroll-request"></p>
  </div>
</div>

app/views/users/withdrawal.html.erb
<%# ユーザー退会確認ページ %>
<div class="users-withdrawal-wrapper">
  <h2>ユーザー退会ページ</h2>

  <p>アカウントの削除ページです。</p>

  <div class="users-withdrawal-button">
    <div class="users-not-delete-button">
      <%= link_to '削除しない', user_path(current_user) %>
    </div>
    <div class="users-delete-button">
      <%= link_to '削除する', user_path(current_user), method: :delete %>
    </div>
  </div>
</div>