config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'genres/index'
  devise_for :admins
  # SNS_login_or_signup_routing
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  def devise_scope(scope)
    constraint = lambda do |request|
      request.env['devise.mapping'] = Devise.mappings[scope]
      true
    end

    constraints(constraint) do
      yield
    end
  end

  # homes_routing
  root 'homes#top'
  get 'homes/about' => 'about'
  get 'welcome' => 'homes#welcome', as: 'welcoming'
  get 'redirect' => 'homes#redirect'

  # Users_routing
  resources :users do
    resource :relationship, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resources :contacts, only: [:new, :index, :show, :create]
    resources :messages, only: :create
    resources :rooms, only: [:create, :show, :index]
  end
  get 'withdrawal' => 'users#withdrawal'

  # User_favorite_routing
  get '/users/:id/favorites' => 'favorites#index', as: 'user_favorites'
  get '/users/:id/favorite_comments' => 'comment_favorites#index', as: 'user_favorite_comments'

  # Genre_routing
  get '/genres' => 'genres#index'
  get '/genres/:genre_id/posts' => 'posts#category', as: 'category_posts'

  # Posts_routing
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end


  # Admin_routing
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show, :update]
    resources :genres, except: [:new]
  end

  get 'search' => 'search#search'

  # Comment_favortite_routing
  resources :comments do
    resource :comment_favorites, only: [:create, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :genre
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :comment_favorites, dependent: :destroy

  attachment :image

  
  # バリデーション
  validates :body, presence: true, length:{maximum: 140}
  
  # ユーザーがそのコメントをお気に入りしているか判断する
  def comment_favorited_by?(user)
    comment_favorites.where(user_id: user.id).exists?
  end

end

app/models/comment_favorite.rb
class CommentFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  attachment :image

  enum is_support_status: [:"対応待ち", :"対応中", :"対応済み"]

  # :バリデーション
  validates :title, presence: true
  validates :body, presence: true

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  # カテゴリーを通してポストを取得、上下させない
  has_many :categories, dependent: :destroy
  has_many :posts, through: :categories, dependent: :destroy

  # バリデーション
  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  # カテゴリーを通してジャンルを取得するので、上下させない
  has_many :categories, dependent: :destroy
  has_many :genres, through: :categories

  attachment :image

  # バリデーション
  validates :title, presence: true
  validates :image, presence: true
  validates :body, presence: true
  validates :genres, presence: true
  validates :closed_on, presence: true

  # ユーザーがその投稿をお気に入りしているか判断する
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 投稿一覧のソート定義
  def self.sort(selection)
    case selection
    when "new"
      return all.order(created_at: :DESC)
    when "old"
      return all.order(created_at: :ASC)
    when "commentable"
      return all.order(closed_on: :DESC)
    when "many_comment"
      return joins(:comments).group(:post_id).order('count(post_id) desc')
    when "many_favorite"
      return joins(:favorites).group(:post_id).order('count(post_id) desc')
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
        #  , omniauth_providers: [:google, :twitter]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorites_posts, through: :favorites, source: :post
  has_many :comment_favorites, dependent: :destroy
  has_many :favorited_comments, through: :comment_favorites, source: :comment
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :image

  # バリデーション
  validates :name, presence: true, length: {maximum: 20}
  validates :introduction, length: {maximum: 200}


  # 自分がフォローしているユーザーとの関連
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  # 自分がフォローされているユーザーとの関連
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    # 今自分（引数のuser)がフォローしようとしているユーザー（レシーバー）がフォローされているユーザーの中から自分がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  protected

  def self.find_for(auth)
    # userが登録されているか確認
    user = User.find_by(email: auth.info.email)
    # なければ作るように処理
    unless user
      user = User.create(email: auth.info.email,
                         name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20],
                         meta:     auth.to_yaml
                        )
    end
    # 作ったユーザーを返してログイン
    return user
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  # before_action :dm_user?, only: :show
  before_action :current_user?, only: :index

  def create
    @room = Room.create
    @user = User.find(params[:user_id])
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/users/#{@user.id}/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    @user1 = current_user
    @user2 = User.find(params[:user_id])
    if Entry.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages.order(created_at:"DESC")
      @new_message = Message.new
      @entries = @room.entries
      @room_user = @entries.where(user_id: :room_id)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @currentEntries = current_user.entries
    myRoomIds = []
    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    @another_entries = Entry.where(room_id: myRoomIds).where.not(user_id: current_user.id)

  end


end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/index.html.erb
<h2>ダイレクトメッセージ</h2>
<% if @another_entries.present? %>
  <% @another_entries.each do |entry| %>
    <table class="dm-index-table">
      <tbody>
          <tr>
            <td class="dm-index-cell">
              <%= attachment_image_tag entry.user, :image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'50x50', class: "user-icon" %>
            </td>
            <td class="dm-index-cell word-break-cell">
              <%= entry.user.name %>
            </td>
            <% if Message.find_by(id: entry.room.message_ids.last).present? %>
            <td class="dm-index-cell word-break-cell">
              <%= Message.find_by(id: entry.room.message_ids.last)&.content %>
            </td>
            <td class="dm-index-cell">
              <%= l Message.find_by(id: entry.room.message_ids.last).created_at%>
            </td>
            <% else %>
            <td class="dm-index-cell">
              まだメッセージはありません
            </td>
            <td class="dm-index-cell">
              ここから始めましょう！
            </td>
            <% end %>
            <td class="dm-index-cell dm-index-last">
              <%= link_to user_room_path(entry.user, entry.room) do %>
                <i class="far fa-envelope dm-index-link"></i>
              <% end %>
            </td>
          </tr>
      </tbody>
    </table>
  <% end %>

<% else %>

  <div class="dm-index-no-msg">
    <p>
      まだDMはありません。<br>相互フォローのユーザーとDMを初めましょう！
    </p>
  </div>

<% end %>

app/views/rooms/show.html.erb
<%# DM詳細ページ %>
<h2>
  <%= @user2.name %>さんとのチャットルーム
</h2>

<div class="dm-show-link">
  <%= link_to 'ユーザー一覧へ戻る', users_path %>
</div>

<div class="new-dm">
  <%= form_for(@new_message, url: user_messages_path) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <%= f.text_area :content, placeholder: "メッセージを入力してください", class:"new-dm-area", require: true %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <%= f.hidden_field :user_id, value: @user2.id %>
    <br>
    <%= button_tag type: "submit" do %>
      <i class="fas fa-arrow-down dm-submit"></i>
    <% end %>
  <% end %>
</div>

<div class="dm-wrapper">
  <% if @messages.present? %>
    <% @messages.each do |msg| %>
      <% if msg.user == @user1 %>
        <div class="user1-message">
          <div class="user1-image">
              <%= attachment_image_tag @user1, :image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'50x50', class: "user-icon" %>
          </div>
          <div class="user1-content">
            <div class="message-ballon1">
              <%= safe_join(msg.content.split("\n"), tag(:br)) %>
            </div>
            <div class="msg_created_at1">
              <%= l msg.created_at %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="user2-message">
          <div class="user2-image">
            <%= attachment_image_tag @user2, :image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg", size:'50x50', class: "user-icon" %>
          <div class="user2-content">
            <div class="message-ballon2">
              <%= safe_join(msg.content.split("\n"), tag(:br)) %>
              <div class="msg_created_at2">
                <%= l msg.created_at %>
              </div>
            </div>
          </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="no-dm">
      <h3>
        まだ<%= @user2.name  %>さんとのチャットは<br>
        ありません。<br>
        これから始めていきましょう！
      </h3>
    </div>
  <% end %>
</div>